/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-116627-g374824cbc7-20240814"
#endif /* AVUTIL_FFVERSION_H */
